"""notarization + embeds + ai_feedback

Revision ID: 270ffe55ed9b
Revises: 5a4df77caff2
Create Date: 2026-05-28 13:15:54.436126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '270ffe55ed9b'
down_revision: Union[str, None] = '5a4df77caff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_embeds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('etag', sa.String(length=128), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_embeds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_embeds_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('ai_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('accepted_text', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_feedback_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_feedback_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('notarizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_num', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.Column('notarized_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notarizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notarizations_document_id'), ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notarizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notarizations_document_id'))

    op.drop_table('notarizations')
    with op.batch_alter_table('ai_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_feedback_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_ai_feedback_document_id'))

    op.drop_table('ai_feedback')
    with op.batch_alter_table('live_embeds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_embeds_workspace_id'))

    op.drop_table('live_embeds')
    # ### end Alembic commands ###
