"""comments + permissions + templates

Revision ID: 2db13900bf0d
Revises: fe83e591899f
Create Date: 2026-05-28 12:57:49.853686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db13900bf0d'
down_revision: Union[str, None] = 'fe83e591899f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('variables_schema', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_template_workspace_name')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('anchor_block_id', sa.String(length=64), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.String(length=255), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_resolved_at'), ['resolved_at'], unique=False)

    op.create_table('document_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('principal_type', sa.String(length=16), nullable=False),
    sa.Column('principal_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'principal_type', 'principal_id', name='uq_doc_permission_principal')
    )
    with op.batch_alter_table('document_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_permissions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_permissions_principal_id'), ['principal_id'], unique=False)

    op.create_table('sharing_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sharing_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sharing_links_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sharing_links_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sharing_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sharing_links_token'))
        batch_op.drop_index(batch_op.f('ix_sharing_links_document_id'))

    op.drop_table('sharing_links')
    with op.batch_alter_table('document_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_permissions_principal_id'))
        batch_op.drop_index(batch_op.f('ix_document_permissions_document_id'))

    op.drop_table('document_permissions')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_resolved_at'))
        batch_op.drop_index(batch_op.f('ix_comments_parent_id'))
        batch_op.drop_index(batch_op.f('ix_comments_document_id'))

    op.drop_table('comments')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_workspace_id'))

    op.drop_table('templates')
    # ### end Alembic commands ###
