"""add workspace_usage

Revision ID: 388b4b5b887c
Revises: 2db13900bf0d
Create Date: 2026-05-28 13:01:13.733674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '388b4b5b887c'
down_revision: Union[str, None] = '2db13900bf0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_usage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'date', 'provider', 'model', name='uq_usage_dimension')
    )
    with op.batch_alter_table('workspace_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_usage_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_usage_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_usage_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_usage_date'))

    op.drop_table('workspace_usage')
    # ### end Alembic commands ###
