"""documents.created_by

Revision ID: 7abc788c2a75
Revises: fb9f4d654256
Create Date: 2026-05-28 16:30:41.300470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7abc788c2a75'
down_revision: Union[str, None] = 'fb9f4d654256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_created_by'), ['created_by'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_created_by'))
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
